#    This file is part of the FElt finite element analysis package.
#    Copyright (C) 1993-1996 Jason I. Gobat and Darren C. Atkinson
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.

# Makefile for a library
# OBJS names the object files
# LIB names the library; it will be removed first unless APPEND is set
# SRCS will be made before OBJS

include $(TOPDIR)/etc/Makefile.conf

all::		$(LIB)

$(LIB)::	$(SRCS) $(OBJS)
		@if [ x$(APPEND) = x ]; then echo $(RM) $(LIB); $(RM) $(LIB); fi
		$(AR) cq $(LIB) $(OBJS)
		$(RANLIB) $(LIB)

clean::;	@$(RM) $(OBJS) $(LIB) core

clobber::;	@$(RM) $(OBJS) $(LIB) $(SRCS) core tags

install::;

depend::;

tags::		*.[chyl]
		ctags -stv *.[chyl]
