/* A lexical scanner generated by flex */

/* scanner skeleton version:
 * $Header$
 */

#define FLEX_SCANNER

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <osfcn.h>

/* use prototypes in function declarations */
#define YY_USE_PROTOS

/* the "const" storage-class-modifier is valid */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#ifdef __STDC__

#ifdef __GNUC__
#include <stddef.h>
void *malloc( size_t );
void free( void* );
#else
#include <stdlib.h>
#endif	/* __GNUC__ */

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */


#ifdef __TURBOC__
#define YY_USE_CONST
#endif


#ifndef YY_USE_CONST
#define const
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
/* we can't get here if it's an ANSI C compiler, or a C++ compiler,
 * so it's got to be a K&R compiler, and therefore there's no standard
 * place from which to include these definitions
 */
char *malloc();
int free();
int read();
#endif


/* amount of stuff to slurp up with each read */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* returned upon end-of-file */
#define YY_END_TOK 0

/* copy whatever the last rule matched to the standard output */

/* cast to (char *) is because for 8-bit chars, yytext is (unsigned char *) */
/* this used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite()
 */
#define ECHO (void) fwrite( (char *) yytext, yyleng, 1, yyout )

/* gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#define YY_INPUT(buf,result,max_size) \
	if ( (result = read( fileno(yyin), (char *) buf, max_size )) < 0 ) \
	    YY_FATAL_ERROR( "read() in flex scanner failed" );
#define YY_NULL 0

/* no semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#define yyterminate() return ( YY_NULL )

/* report a fatal error */

/* The funky do-while is used to turn this macro definition into
 * a single C statement (which needs a semi-colon terminator).
 * This avoids problems with code like:
 *
 * 	if ( something_happens )
 *		YY_FATAL_ERROR( "oops, the something happened" );
 *	else
 *		everything_okay();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the YY_FATAL_ERROR() call.
 */

#define YY_FATAL_ERROR(msg) \
	do \
		{ \
		(void) fputs( msg, stderr ); \
		(void) putc( '\n', stderr ); \
		exit( 1 ); \
		} \
	while ( 0 )

/* default yywrap function - always treat EOF as an EOF */
#define yywrap() 1

/* enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN
 */
#define BEGIN yy_start = 1 + 2 *

/* action number for EOF rule of a given start state */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* special action meaning "start processing a new file" */
#define YY_NEW_FILE \
	do \
		{ \
		yy_init_buffer( yy_current_buffer, yyin ); \
		yy_load_buffer_state(); \
		} \
	while ( 0 )

/* default declaration of generated scanner - a define so the user can
 * easily add parameters
 */
#define YY_DECL int yylex YY_PROTO(( void )) 

/* code executed at the end of each rule */
#define YY_BREAK break;

#define YY_END_OF_BUFFER_CHAR 0

#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE (YY_READ_BUF_SIZE * 2) /* size of default input buffer */
#endif

typedef struct yy_buffer_state *YY_BUFFER_STATE;

#define YY_CHAR char
# line 1 "lexer.l"
#define INITIAL 0
# line 2 "lexer.l"
/*
    This file is part of the FElt finite element analysis package.
    Copyright (C) 1993,1994 Jason I. Gobat and Darren C. Atkinson

    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
*/

/************************************************************************
 * File:	lexer.l							*
 *									*
 * Description:	This file contains the flex specification for the	*
 *		lexical analyzer for the corduroy element generator.	*
 ************************************************************************/

# include <stdio.h>
# include <string.h>
# include "error.h"
# include "generator.h"

# ifdef DOS
# include "yxtab.h"
# else
# include "y.tab.h"
# endif

# undef atof
extern double atof ( );


static char *filename;
static void  update_line PROTO ((void));
#define comment 1
# line 54 "lexer.l"

/* done after the current pattern has been matched and before the
 * corresponding action - sets up yytext
 */
#define YY_DO_BEFORE_ACTION \
	yytext = yy_bp; \
	yyleng = yy_cp - yy_bp; \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* return all but the first 'n' matched characters back to the input stream */
#define yyless(n) \
	do \
		{ \
		/* undo effects of setting up yytext */ \
		*yy_cp = yy_hold_char; \
		yy_c_buf_p = yy_cp = yy_bp + n; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext )


struct yy_buffer_state
    {
    FILE *yy_input_file;

    YY_CHAR *yy_ch_buf;		/* input buffer */
    YY_CHAR *yy_buf_pos;	/* current position in input buffer */

    /* size of input buffer in bytes, not including room for EOB characters */
    int yy_buf_size;	

    /* number of characters read into yy_ch_buf, not including EOB characters */
    int yy_n_chars;

    int yy_eof_status;		/* whether we've seen an EOF on this buffer */
#define EOF_NOT_SEEN 0
    /* "pending" happens when the EOF has been seen but there's still
     * some text process
     */
#define EOF_PENDING 1
#define EOF_DONE 2
    };

static YY_BUFFER_STATE yy_current_buffer;

/* we provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state"
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed */
static YY_CHAR yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */



#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

#ifndef YY_USER_INIT
#define YY_USER_INIT
#endif

extern YY_CHAR *yytext;
extern int yyleng;
extern FILE *yyin, *yyout;

YY_CHAR *yytext;
int yyleng;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

#define YY_END_OF_BUFFER 76
typedef int yy_state_type;
static const short int yy_acclist[356] =
    {   0,
       69,   69,   76,   74,   75,   66,   74,   75,   67,   75,
       74,   75,   74,   75,   74,   75,16449,   74,   75,   74,
       75,   74,   75,   59,   74,   75,   74,   75,   74,   75,
       74,   75,   63,   74,   75,   63,   74,   75,   63,   74,
       75,   63,   74,   75,   63,   74,   75,   63,   74,   75,
       63,   74,   75,   63,   74,   75,   63,   74,   75,   63,
       74,   75,   63,   74,   75,   63,   74,   75,   63,   74,
       75,   63,   74,   75,   63,   74,   75,   63,   74,   75,
       63,   74,   75,   63,   74,   75,   63,   74,   75,   63,
       74,   75,   63,   74,   75,   74,   75,   69,   75,   70,

       75,   71,   75,   66,   54,   64,16449, 8257,   51,   62,
       68,   61,   59,   57,   55,   53,   56,   58,   63,   63,
       63,   63,   63,   63,   63,   63,   63,   63,   63,   63,
       63,   63,   63,   63,   63,   63,   63,   63,   63,   63,
       63,   63,   63,   63,   63,   63,   63,   63,   63,   63,
       63,   52,   69,   70,   71,   72,   71,   73,   61,   62,
       60,   63,   63,   63,   63,   63,    8,   63,   63,   63,
        6,   63,   11,   63,   63,   63,   63,   63,   63,   63,
       63,   63,   12,   63,   63,   63,   63,   63,   63,   10,
       63,   63,   63,   63,    7,   63,   63,   63,    9,   63,

       63,   63,   62,   61,   63,   63,   63,   63,   17,   63,
       63,   63,   63,   63,   33,   19,   63,   63,   18,   63,
        2,   63,   63,   63,   63,    1,   63,   63,   63,   63,
       48,   47,   63,   63,   63,   63,   63,   63,   14,   63,
       63,   63,   63,   61,   62,   63,   63,   63,   63,   63,
       63,   45,   63,   16,   63,   50,   15,   63,   63,   63,
       13,   63,   63,   63,   63,   63,   63,   63,   35,   63,
       63,   63,   63,   63,   63,   63,   63,   63,   63,   46,
       20,   63,   63,   63,   63,   63,   63,   63,   63,   32,
       42,   63,   43,   44,   63,   63,   63,   63,   63,   63,

       34,   63,   63,   63,   63,   63,   39,   40,   41,   63,
       63,   63,   63,   63,   63,   63,   63,   63,   49,   63,
       63,   63,   30,   25,   63,   63,   63,   63,   36,   37,
       38,    4,   63,   63,   63,   63,   24,   63,   63,   29,
       63,   21,   63,   63,   27,   23,   63,   63,   31,   63,
       28,    5,   26,    3,   22
    } ;

static const short int yy_accept[389] =
    {   0,
        1,    1,    1,    2,    3,    4,    6,    9,   11,   13,
       15,   18,   20,   22,   24,   27,   29,   31,   33,   36,
       39,   42,   45,   48,   51,   54,   57,   60,   63,   66,
       69,   72,   75,   78,   81,   84,   87,   90,   93,   96,
       98,  100,  102,  104,  105,  106,  106,  107,  108,  109,
      110,  111,  112,  113,  114,  114,  115,  116,  117,  118,
      119,  120,  121,  122,  123,  124,  125,  126,  127,  128,
      129,  130,  131,  132,  133,  134,  135,  136,  137,  138,
      139,  140,  141,  142,  143,  144,  145,  146,  147,  148,
      149,  150,  151,  152,  152,  152,  152,  153,  154,  155,

      156,  157,  158,  159,  159,  161,  161,  161,  162,  163,
      164,  165,  166,  167,  169,  170,  171,  173,  175,  176,
      177,  178,  179,  180,  181,  182,  183,  185,  186,  187,
      188,  189,  190,  192,  193,  194,  195,  197,  198,  199,
      201,  202,  203,  203,  203,  203,  203,  203,  203,  203,
      204,  204,  204,  205,  206,  207,  208,  209,  211,  212,
      213,  214,  215,  215,  216,  218,  219,  221,  223,  224,
      225,  226,  228,  229,  230,  231,  231,  232,  232,  233,
      234,  235,  236,  237,  238,  239,  241,  242,  243,  244,
      244,  244,  244,  244,  244,  244,  244,  246,  247,  248,

      249,  250,  251,  252,  252,  253,  254,  256,  256,  257,
      259,  260,  261,  263,  264,  265,  266,  267,  268,  269,
      269,  270,  271,  272,  273,  274,  274,  274,  274,  274,
      274,  274,  275,  276,  277,  277,  278,  279,  280,  280,
      281,  283,  284,  285,  286,  287,  288,  289,  290,  290,
      290,  291,  291,  292,  293,  293,  293,  293,  293,  293,
      293,  293,  294,  294,  295,  296,  296,  297,  298,  299,
      300,  301,  301,  302,  303,  304,  305,  306,  306,  306,
      307,  307,  307,  308,  308,  308,  309,  309,  309,  310,
      311,  311,  312,  313,  313,  314,  315,  316,  317,  317,

      318,  318,  318,  319,  319,  319,  319,  319,  320,  320,
      321,  322,  322,  323,  323,  324,  326,  327,  327,  327,
      328,  328,  328,  329,  329,  330,  330,  331,  331,  332,
      333,  334,  335,  335,  336,  337,  337,  337,  339,  339,
      339,  340,  340,  341,  342,  342,  344,  345,  345,  345,
      345,  345,  346,  346,  348,  348,  349,  349,  349,  349,
      349,  349,  350,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  352,  352,  352,  352,  352,  353,  353,  353,
      353,  353,  353,  354,  355,  355,  356,  356
    } ;

static const YY_CHAR yy_ec[128] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    1,    1,    8,    1,    1,
        1,    9,   10,    1,   11,   12,   13,   14,   15,   16,
       16,   16,   16,   16,   16,   16,   16,    1,    1,   17,
       18,   19,    1,    1,   21,   22,   23,   24,   25,   26,
       27,   28,   29,   20,   30,   31,   32,   33,   34,   35,
       36,   37,   38,   39,   40,   41,   42,   43,   44,   45,
        1,    1,    1,    1,   20,    1,   21,   22,   23,   24,

       25,   26,   27,   28,   29,   20,   30,   31,   32,   33,
       34,   35,   36,   37,   38,   39,   40,   41,   42,   43,
       44,   45,    1,   46,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[47] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    1,
        1,    1,    1,    3,    3,    3,    1,    1,    1,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    1
    } ;

static const short int yy_base[394] =
    {   0,
        0,    0,   44,   45,  565,  566,   47,  566,  546,  557,
      559,  553,   41,  551,   46,   46,  541,   47,    0,  525,
       33,   25,  525,   41,   47,  519,   39,  534,   46,   48,
      514,   55,  513,   56,   56,   65,  541,  540,  539,  503,
      545,  566,   84,   86,  566,  541,  566,  543,  566,  566,
       89,  566,   92,   97,  105,  566,  566,  566,  566,  566,
        0,  518,  504,  514,  513,   85,  512,  515,  515,  503,
      515,  502,  501,  505,  502,  497,  496,  497,  502,   55,
      495,  495,  489,  483,  503,  482,  491,  488,  483,  498,
      485,  486,  487,   91,   92,   93,  566,  512,  566,  124,

      566,  129,  566,  125,  129,  136,  141,  144,   62,  481,
      490,  481,  473,  481,  476,  476,  159,    0,  469,  472,
      481,  480,  478,  468,  466,  475,  147,  474,  162,  163,
      476,  476,    0,  472,  470,  469,  453,  453,  454,    0,
      461,  468,  448,  447,  446,  445,  444,  443,  155,  158,
      168,  171,  174,  447,  447,  456,  449,    0,  439,  444,
      189,  451,  190,  566,    0,  438,    0,    0,  193,  435,
      452,  451,  457,  433,  432,  194,  566,  197,  566,  443,
      445,  429,  428,  198,  426,    0,  424,  429,  428,  428,
      428,  426,  426,  424,  424,  189,  203,  431,  422,  431,

      447,  413,  409,  218,  566,  415,    0,  219,  566,    0,
      222,  410,    0,  417,  416,  407,  409,  413,  403,  223,
      566,  406,  227,  226,  412,  416,  412,  414,  410,  412,
      408,  230,  231,  395,  404,  409,  391,  389,  248,  566,
        0,  388,  405,  249,  394,  393,  398,  393,  252,  181,
      566,  253,  566,  381,  395,  256,  394,  257,  393,  260,
      261,  566,  278,  566,  373,  379,  386,  380,  402,  384,
      380,  279,  566,  381,  388,  397,  383,  375,  371,  373,
      366,  282,  566,  365,  283,  566,  364,  286,  566,  287,
      371,  366,  369,  358,  364,  290,  372,  355,  118,  372,

      367,  367,  369,  291,  308,  309,  312,  566,  365,  349,
      363,  342,  356,  313,  566,    0,  359,  345,  346,  335,
      331,  337,  322,  316,  566,  317,  566,  320,  566,  566,
      321,  337,  320,  330,  300,  309,  296,    0,  307,  338,
      325,  339,  566,  297,  282,    0,  285,  282,  281,  266,
      342,  566,  266,    0,  343,  246,  239,  251,  233,  244,
      346,  566,  264,  218,  212,  347,  205,  215,  200,  182,
      350,  566,  182,  172,  148,  146,  566,  119,  102,  108,
       86,   62,  566,  566,   59,  566,  566,  368,  371,  374,
       49,  377,  380

    } ;

static const short int yy_def[394] =
    {   0,
      387,    1,  388,  388,  387,  387,  387,  387,  387,  389,
      390,  387,  387,  387,  387,  387,  387,  387,  391,  391,
      391,  391,  391,  391,  391,  391,  391,  391,  391,  391,
      391,  391,  391,  391,  391,  391,  391,  391,  391,  387,
      392,  387,  393,  387,  387,  389,  387,  390,  387,  387,
      387,  387,  387,  387,  387,  387,  387,  387,  387,  387,
      391,  391,  391,  391,  391,  391,  391,  391,  391,  391,
      391,  391,  391,  391,  391,  391,  391,  391,  391,  391,
      391,  391,  391,  391,  391,  391,  391,  391,  391,  391,
      391,  391,  391,  387,  387,  387,  387,  392,  387,  393,

      387,  393,  387,  387,  387,  387,  387,  387,  391,  391,
      391,  391,  391,  391,  391,  391,  391,  391,  391,  391,
      391,  391,  391,  391,  391,  391,  391,  391,  391,  391,
      391,  391,  391,  391,  391,  391,  391,  391,  391,  391,
      391,  391,  387,  387,  387,  387,  387,  387,  387,  387,
      387,  387,  387,  391,  391,  391,  391,  391,  391,  391,
      391,  391,  387,  387,  391,  391,  391,  391,  391,  391,
      391,  391,  391,  391,  391,  387,  387,  387,  387,  391,
      391,  391,  391,  391,  391,  391,  391,  391,  391,  387,
      387,  387,  387,  387,  387,  387,  387,  391,  391,  391,

      391,  391,  391,  387,  387,  391,  391,  387,  387,  391,
      391,  391,  391,  391,  391,  391,  391,  391,  391,  387,
      387,  391,  391,  391,  391,  387,  387,  387,  387,  387,
      387,  391,  391,  391,  387,  391,  391,  391,  387,  387,
      391,  391,  391,  391,  391,  391,  391,  391,  387,  387,
      387,  387,  387,  391,  387,  387,  387,  387,  387,  387,
      387,  387,  387,  387,  391,  387,  391,  391,  391,  391,
      391,  387,  387,  391,  391,  391,  391,  387,  387,  391,
      387,  387,  387,  387,  387,  387,  387,  387,  387,  391,
      387,  391,  391,  387,  391,  391,  391,  391,  387,  391,

      387,  387,  391,  387,  387,  387,  387,  387,  387,  391,
      391,  387,  391,  387,  387,  391,  391,  387,  387,  391,
      387,  387,  391,  387,  387,  387,  387,  387,  387,  387,
      391,  391,  387,  391,  391,  387,  387,  391,  387,  387,
      391,  387,  387,  391,  387,  391,  391,  387,  387,  387,
      387,  387,  387,  391,  387,  391,  387,  387,  387,  387,
      387,  387,  391,  387,  387,  387,  387,  387,  387,  387,
      387,  387,  387,  387,  387,  387,  387,  387,  387,  387,
      387,  387,  387,  387,  387,  387,    0,  387,  387,  387,
      387,  387,  387

    } ;

static const short int yy_nxt[613] =
    {   0,
        6,    7,    8,    7,    9,   10,   11,   12,    6,    6,
        6,   13,   14,   15,   15,   15,   16,   17,   18,   19,
       20,   21,   22,   23,   24,   25,   26,   27,   19,   28,
       29,   30,   31,   19,   32,   33,   34,   35,   36,   19,
       19,   19,   37,   38,   39,   40,   42,   42,   44,   65,
       44,   61,   43,   43,   51,   51,   51,   53,   66,   54,
       54,   54,   56,   57,   59,   60,   63,   71,   80,   64,
       55,   68,   75,   69,   78,   83,   81,   72,   73,   79,
       86,  386,   76,   70,   88,   91,  101,   44,   84,   44,
      385,   89,  102,  128,   90,   87,  103,  129,   92,  154,

      155,   93,   51,   51,   51,  105,  105,  105,   53,  384,
       54,   54,   54,  104,  107,  107,  106,  113,  108,  108,
      108,   55,  114,  143,  145,  147,  101,  144,  146,  148,
      383,  101,  387,  382,  149,  149,  387,  102,  150,  150,
      150,  103,  105,  105,  105,  152,  152,  381,  318,  153,
      153,  153,  319,  151,  108,  108,  108,  108,  108,  108,
      163,  173,  163,  176,  178,  176,  178,  174,  150,  150,
      150,  150,  150,  150,  380,  379,  164,  196,  196,  177,
      179,  197,  197,  197,  153,  153,  153,  153,  153,  153,
      204,  163,  204,  163,  208,  176,  208,  176,  178,  220,

      178,  220,  197,  197,  197,  278,  205,  164,  378,  377,
      209,  177,  376,  279,  179,  221,  197,  197,  197,  204,
      208,  204,  208,  239,  220,  239,  220,  252,  249,  252,
      249,  261,  263,  261,  263,  205,  209,  250,  375,  240,
      221,  374,  373,  253,  251,  370,  369,  262,  264,  239,
      272,  239,  272,  249,  252,  249,  252,  282,  285,  282,
      285,  288,  261,  288,  261,  240,  273,  368,  367,  251,
      253,  366,  365,  283,  286,  364,  363,  289,  262,  263,
      272,  263,  272,  282,  285,  282,  285,  288,  307,  288,
      307,  314,  324,  314,  324,  264,  273,  360,  359,  283,

      286,  358,  357,  289,  308,  356,  355,  315,  325,  326,
      328,  326,  328,  307,  314,  307,  314,  324,  326,  324,
      326,  328,  342,  328,  342,  327,  329,  354,  353,  308,
      315,  350,  349,  325,  327,  348,  347,  329,  343,  351,
      342,  351,  342,  351,  361,  351,  361,  361,  371,  361,
      371,  371,  346,  371,  345,  352,  343,  344,  341,  352,
      362,  340,  339,  362,  372,  338,  337,  372,   41,   41,
       41,   46,   46,   46,   48,   48,   48,   98,  336,   98,
      100,  100,  100,  335,  334,  333,  332,  331,  330,  323,
      322,  321,  320,  317,  316,  313,  312,  311,  310,  309,

      306,  305,  304,  303,  302,  301,  300,  299,  298,  297,
      296,  295,  294,  293,  292,  291,  290,  287,  284,  281,
      280,  277,  276,  275,  274,  271,  270,  269,  268,  267,
      266,  265,  260,  259,  258,  257,  256,  255,  254,  248,
      247,  246,  245,  244,  243,  242,  241,  238,  237,  236,
      235,  234,  233,  232,  231,  230,  229,  228,  227,  226,
      225,  224,  223,  222,  219,  218,  217,  216,  215,  214,
      213,  212,  211,  210,  207,  206,  203,  202,  201,  200,
      199,  198,  195,  194,  193,  192,  191,  190,  189,  188,
      187,  186,  185,  184,  183,  182,  181,  180,  175,  172,

      171,  170,  169,  168,  167,  166,  165,  162,  161,  160,
      159,  158,  157,  156,   99,  142,  141,  140,  139,  138,
      137,  136,  135,  134,  133,  132,  131,  130,  127,  126,
      125,  124,  123,  122,  121,  120,  119,  118,  117,  116,
      115,  112,  111,  110,  109,   49,   47,   99,   97,   96,
       95,   94,   85,   82,   77,   74,   67,   62,   58,   52,
       50,   49,   47,   45,  387,    5,  387,  387,  387,  387,
      387,  387,  387,  387,  387,  387,  387,  387,  387,  387,
      387,  387,  387,  387,  387,  387,  387,  387,  387,  387,
      387,  387,  387,  387,  387,  387,  387,  387,  387,  387,

      387,  387,  387,  387,  387,  387,  387,  387,  387,  387,
      387,  387
    } ;

static const short int yy_chk[613] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    3,    4,    7,   22,
        7,  391,    3,    4,   13,   13,   13,   15,   22,   15,
       15,   15,   16,   16,   18,   18,   21,   25,   30,   21,
       15,   24,   27,   24,   29,   32,   30,   25,   25,   29,
       34,  385,   27,   24,   35,   36,   43,   44,   32,   44,
      382,   35,   43,   80,   35,   34,   43,   80,   36,  109,

      109,   36,   51,   51,   51,   53,   53,   53,   54,  381,
       54,   54,   54,   51,   55,   55,   53,   66,   55,   55,
       55,   54,   66,   94,   95,   96,  100,   94,   95,   96,
      380,  102,  100,  379,  104,  104,  100,  102,  104,  104,
      104,  102,  105,  105,  105,  106,  106,  378,  299,  106,
      106,  106,  299,  105,  107,  107,  107,  108,  108,  108,
      117,  127,  117,  129,  130,  129,  130,  127,  149,  149,
      149,  150,  150,  150,  376,  375,  117,  151,  151,  129,
      130,  151,  151,  151,  152,  152,  152,  153,  153,  153,
      161,  163,  161,  163,  169,  176,  169,  176,  178,  184,

      178,  184,  196,  196,  196,  250,  161,  163,  374,  373,
      169,  176,  370,  250,  178,  184,  197,  197,  197,  204,
      208,  204,  208,  211,  220,  211,  220,  224,  223,  224,
      223,  232,  233,  232,  233,  204,  208,  223,  369,  211,
      220,  368,  367,  224,  223,  365,  364,  232,  233,  239,
      244,  239,  244,  249,  252,  249,  252,  256,  258,  256,
      258,  260,  261,  260,  261,  239,  244,  363,  360,  249,
      252,  359,  358,  256,  258,  357,  356,  260,  261,  263,
      272,  263,  272,  282,  285,  282,  285,  288,  290,  288,
      290,  296,  304,  296,  304,  263,  272,  353,  350,  282,

      285,  349,  348,  288,  290,  347,  345,  296,  304,  305,
      306,  305,  306,  307,  314,  307,  314,  324,  326,  324,
      326,  328,  331,  328,  331,  305,  306,  344,  341,  307,
      314,  339,  337,  324,  326,  336,  335,  328,  331,  340,
      342,  340,  342,  351,  355,  351,  355,  361,  366,  361,
      366,  371,  334,  371,  333,  340,  342,  332,  323,  351,
      355,  322,  321,  361,  366,  320,  319,  371,  388,  388,
      388,  389,  389,  389,  390,  390,  390,  392,  318,  392,
      393,  393,  393,  317,  313,  312,  311,  310,  309,  303,
      302,  301,  300,  298,  297,  295,  294,  293,  292,  291,

      287,  284,  281,  280,  279,  278,  277,  276,  275,  274,
      271,  270,  269,  268,  267,  266,  265,  259,  257,  255,
      254,  248,  247,  246,  245,  243,  242,  238,  237,  236,
      235,  234,  231,  230,  229,  228,  227,  226,  225,  222,
      219,  218,  217,  216,  215,  214,  212,  206,  203,  202,
      201,  200,  199,  198,  195,  194,  193,  192,  191,  190,
      189,  188,  187,  185,  183,  182,  181,  180,  175,  174,
      173,  172,  171,  170,  166,  162,  160,  159,  157,  156,
      155,  154,  148,  147,  146,  145,  144,  143,  142,  141,
      139,  138,  137,  136,  135,  134,  132,  131,  128,  126,

      125,  124,  123,  122,  121,  120,  119,  116,  115,  114,
      113,  112,  111,  110,   98,   93,   92,   91,   90,   89,
       88,   87,   86,   85,   84,   83,   82,   81,   79,   78,
       77,   76,   75,   74,   73,   72,   71,   70,   69,   68,
       67,   65,   64,   63,   62,   48,   46,   41,   40,   39,
       38,   37,   33,   31,   28,   26,   23,   20,   17,   14,
       12,   11,   10,    9,    5,  387,  387,  387,  387,  387,
      387,  387,  387,  387,  387,  387,  387,  387,  387,  387,
      387,  387,  387,  387,  387,  387,  387,  387,  387,  387,
      387,  387,  387,  387,  387,  387,  387,  387,  387,  387,

      387,  387,  387,  387,  387,  387,  387,  387,  387,  387,
      387,  387
    } ;

static yy_state_type yy_last_accepting_state;
static YY_CHAR *yy_last_accepting_cpos;

static yy_state_type yy_state_buf[YY_BUF_SIZE + 2], *yy_state_ptr;
static YY_CHAR *yy_full_match;
static int yy_lp;
static int yy_looking_for_trail_begin = 0;
static int yy_full_lp;
static int *yy_full_state;
#define YY_TRAILING_MASK 0x2000
#define YY_TRAILING_HEAD_MASK 0x4000
#define REJECT \
{ \
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */ \
yy_cp = yy_full_match; /* restore poss. backed-over text */ \
yy_lp = yy_full_lp; /* restore orig. accepting pos. */ \
yy_state_ptr = yy_full_state; /* restore orig. state */ \
yy_current_state = *yy_state_ptr; /* restore curr. state */ \
++yy_lp; \
goto find_rule; \
}
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0

/* these variables are all declared out here so that section 3 code can
 * manipulate them
 */
/* points to current character in buffer */
static YY_CHAR *yy_c_buf_p = (YY_CHAR *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yyunput YY_PROTO(( YY_CHAR c, YY_CHAR *buf_ptr ));
void yyrestart YY_PROTO(( FILE *input_file ));
void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));

#define yy_new_buffer yy_create_buffer

#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif

YY_DECL
    {
    register yy_state_type yy_current_state;
    register YY_CHAR *yy_cp, *yy_bp;
    register int yy_act;





    if ( yy_init )
	{
	YY_USER_INIT;

	if ( ! yy_start )
	    yy_start = 1;	/* first start state */

	if ( ! yyin )
	    yyin = stdin;

	if ( ! yyout )
	    yyout = stdout;

	if ( yy_current_buffer )
	    yy_init_buffer( yy_current_buffer, yyin );
	else
	    yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_load_buffer_state();

	yy_init = 0;
	}

    while ( 1 )		/* loops until end-of-file is reached */
	{
	yy_cp = yy_c_buf_p;

	/* support of yytext */
	*yy_cp = yy_hold_char;

	/* yy_bp points to the position in yy_ch_buf of the start of the
	 * current run.
	 */
	yy_bp = yy_cp;

	yy_current_state = yy_start;
	yy_state_ptr = yy_state_buf;
	*yy_state_ptr++ = yy_current_state;
yy_match:
	do
	    {
	    register YY_CHAR yy_c = yy_ec[*yy_cp];
	    while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = yy_def[yy_current_state];
		if ( yy_current_state >= 388 )
		    yy_c = yy_meta[yy_c];
		}
	    yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	    *yy_state_ptr++ = yy_current_state;
	    ++yy_cp;
	    }
	while ( yy_current_state != 387 );

yy_find_action:
	yy_current_state = *--yy_state_ptr;
	yy_lp = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backtracking */
	for ( ; ; ) /* until we find what rule we matched */
	    {
	    if ( yy_lp && yy_lp < yy_accept[yy_current_state + 1] )
		{
		yy_act = yy_acclist[yy_lp];
		if ( yy_act & YY_TRAILING_HEAD_MASK ||
		     yy_looking_for_trail_begin )
		    {
		    if ( yy_act == yy_looking_for_trail_begin )
			{
			yy_looking_for_trail_begin = 0;
			yy_act &= ~YY_TRAILING_HEAD_MASK;
			break;
			}
		    }
		else if ( yy_act & YY_TRAILING_MASK )
		    {
		    yy_looking_for_trail_begin = yy_act & ~YY_TRAILING_MASK;
		    yy_looking_for_trail_begin |= YY_TRAILING_HEAD_MASK;
		    }
		else
		    {
		    yy_full_match = yy_cp;
		    yy_full_state = yy_state_ptr;
		    yy_full_lp = yy_lp;
		    break;
		    }
		++yy_lp;
		goto find_rule;
		}
	    --yy_cp;
	    yy_current_state = *--yy_state_ptr;
	    yy_lp = yy_accept[yy_current_state];
	    }

	YY_DO_BEFORE_ACTION;
	YY_USER_ACTION;

do_action:	/* this label is used only to access EOF actions */


	switch ( yy_act )
	    {

/* Section headings */

case 1:
# line 61 "lexer.l"
{return LINE;}
	YY_BREAK
case 2:
# line 62 "lexer.l"
{return GRID;}
	YY_BREAK
case 3:
# line 63 "lexer.l"
{return QUADGRID;}
	YY_BREAK
case 4:
# line 64 "lexer.l"
{return BRICKGRID;}
	YY_BREAK
case 5:
# line 65 "lexer.l"
{return TRIMESH;}
	YY_BREAK
case 6:
# line 66 "lexer.l"
{return END;}
	YY_BREAK

/* Reserved words (in expression or right hand side of assignment) */

case 7:
# line 73 "lexer.l"
{return SIN;}
	YY_BREAK
case 8:
# line 74 "lexer.l"
{return COS;}
	YY_BREAK
case 9:
# line 75 "lexer.l"
{return TAN;}
	YY_BREAK
case 10:
# line 76 "lexer.l"
{return POW;}
	YY_BREAK
case 11:
# line 77 "lexer.l"
{return EXP;}
	YY_BREAK
case 12:
# line 78 "lexer.l"
{return LOG;}
	YY_BREAK
case 13:
# line 79 "lexer.l"
{return LOG10;}
	YY_BREAK
case 14:
# line 80 "lexer.l"
{return SQRT;}
	YY_BREAK
case 15:
# line 81 "lexer.l"
{return HYPOT;}
	YY_BREAK
case 16:
# line 82 "lexer.l"
{return FLOOR;}
	YY_BREAK
case 17:
# line 83 "lexer.l"
{return CEIL;}
	YY_BREAK
case 18:
# line 84 "lexer.l"
{return FMOD;}
	YY_BREAK
case 19:
# line 85 "lexer.l"
{return FABS;}
	YY_BREAK
case 20:
# line 86 "lexer.l"
{return LINEAR;}
	YY_BREAK
case 21:
# line 87 "lexer.l"
{return LOGARITHMIC;}
	YY_BREAK
case 22:
# line 88 "lexer.l"
{return REVERSE_LOGARITHMIC;}
	YY_BREAK
case 23:
# line 89 "lexer.l"
{return COSINUSOIDAL;}
	YY_BREAK
case 24:
# line 90 "lexer.l"
{return SINUSOIDAL;}
	YY_BREAK
case 25:
# line 91 "lexer.l"
{return PARABOLIC;}
	YY_BREAK
case 26:
# line 92 "lexer.l"
{return REVERSE_PARABOLIC;}
	YY_BREAK

/* Assignments */

case 27:
# line 98 "lexer.l"
{return NODE_EQ;}
	YY_BREAK
case 28:
# line 99 "lexer.l"
{return ELEMENT_EQ;}
	YY_BREAK
case 29:
# line 100 "lexer.l"
{return CONSTRAINT_EQ;}
	YY_BREAK
case 30:
# line 101 "lexer.l"
{return MATERIAL_EQ;}
	YY_BREAK
case 31:
# line 102 "lexer.l"
{return TYPE_EQ;}
	YY_BREAK
case 32:
# line 103 "lexer.l"
{return START_EQ;}
	YY_BREAK
case 33:
# line 104 "lexer.l"
{return END_EQ;}
	YY_BREAK
case 34:
# line 105 "lexer.l"
{return NUMBER_EQ;}
	YY_BREAK
case 35:
# line 106 "lexer.l"
{return RULE_EQ;}
	YY_BREAK
case 36:
# line 107 "lexer.l"
{return X_NUMBER_EQ;}
	YY_BREAK
case 37:
# line 108 "lexer.l"
{return Y_NUMBER_EQ;}
	YY_BREAK
case 38:
# line 109 "lexer.l"
{return Z_NUMBER_EQ;}
	YY_BREAK
case 39:
# line 110 "lexer.l"
{return X_RULE_EQ;}
	YY_BREAK
case 40:
# line 111 "lexer.l"
{return Y_RULE_EQ;}
	YY_BREAK
case 41:
# line 112 "lexer.l"
{return Z_RULE_EQ;}
	YY_BREAK
case 42:
# line 113 "lexer.l"
{return TOLIN_EQ;}
	YY_BREAK
case 43:
# line 114 "lexer.l"
{return ANGSPC_EQ;}
	YY_BREAK
case 44:
# line 115 "lexer.l"
{return ANGTOL_EQ;}
	YY_BREAK
case 45:
# line 116 "lexer.l"
{return DMIN_EQ;}
	YY_BREAK
case 46:
# line 117 "lexer.l"
{return KAPPA_EQ;}
	YY_BREAK
case 47:
# line 118 "lexer.l"
{return MIN_EQ;}
	YY_BREAK
case 48:
# line 119 "lexer.l"
{return MAX_EQ;}
	YY_BREAK
case 49:
# line 120 "lexer.l"
{return BOUNDARY_EQ;}
	YY_BREAK
case 50:
# line 121 "lexer.l"
{return HOLE_EQ;}
	YY_BREAK

/* Operators */

case 51:
# line 128 "lexer.l"
{return AND;}
	YY_BREAK
case 52:
# line 129 "lexer.l"
{return OR;}
	YY_BREAK
case 53:
# line 130 "lexer.l"
{return EQUALS;}
	YY_BREAK
case 54:
# line 131 "lexer.l"
{return NEQUAL;}
	YY_BREAK
case 55:
# line 132 "lexer.l"
{return LT_EQ;}
	YY_BREAK
case 56:
# line 133 "lexer.l"
{return GT_EQ;}
	YY_BREAK
case 57:
# line 134 "lexer.l"
{return LSHIFT;}
	YY_BREAK
case 58:
# line 135 "lexer.l"
{return RSHIFT;}
	YY_BREAK

/* Numbers and names */

case 59:
# line 142 "lexer.l"
{yylval.i = atoi (yytext); return INTEGER;}
	YY_BREAK
case 60:
# line 143 "lexer.l"
{yylval.d = atof (yytext); return DOUBLE;}
	YY_BREAK
case 61:
# line 144 "lexer.l"
{yylval.d = atof (yytext); return DOUBLE;}
	YY_BREAK
case 62:
# line 145 "lexer.l"
{yylval.d = atof (yytext); return DOUBLE;}
	YY_BREAK
case 63:
# line 147 "lexer.l"
{yylval.s = strdup (yytext); return NAME;}
	YY_BREAK
case 64:
# line 148 "lexer.l"
{yylval.s = strdup (yytext + 1);
				 yylval.s [yyleng - 2] = 0; return NAME;}
	YY_BREAK

/* Comments, white space, and remaining preprocessor lines (the comment
   rules are straight from the flex documentation). */

case 65:
# line 157 "lexer.l"
{update_line ( );}
	YY_BREAK
case 66:
# line 158 "lexer.l"
{}
	YY_BREAK
case 67:
# line 159 "lexer.l"
{generator.line ++;}
	YY_BREAK
case 68:
# line 160 "lexer.l"
{BEGIN comment;}
	YY_BREAK
case 69:
# line 162 "lexer.l"
{}
	YY_BREAK
case 70:
# line 163 "lexer.l"
{generator.line ++;}
	YY_BREAK
case 71:
# line 164 "lexer.l"
{}
	YY_BREAK
case 72:
# line 165 "lexer.l"
{generator.line ++;}
	YY_BREAK
case 73:
# line 166 "lexer.l"
{BEGIN INITIAL;}
	YY_BREAK
case 74:
# line 168 "lexer.l"
{return *yytext;}
	YY_BREAK
case 75:
# line 170 "lexer.l"
ECHO;
	YY_BREAK
	    case YY_STATE_EOF(INITIAL):
	    case YY_STATE_EOF(comment):
		yyterminate();

	    case YY_END_OF_BUFFER:
		{
		/* amount of text matched not including the EOB char */
		int yy_amount_of_matched_text = yy_cp - yytext - 1;

		/* undo the effects of YY_DO_BEFORE_ACTION */
		*yy_cp = yy_hold_char;

		/* note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the end-
		 * of-buffer state).  Contrast this with the test in yyinput().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
		    /* this was really a NUL */
		    {
		    yy_state_type yy_next_state;

		    yy_c_buf_p = yytext + yy_amount_of_matched_text;

		    yy_current_state = yy_get_previous_state();

		    /* okay, we're now positioned to make the
		     * NUL transition.  We couldn't have
		     * yy_get_previous_state() go ahead and do it
		     * for us because it doesn't know how to deal
		     * with the possibility of jamming (and we
		     * don't want to build jamming into it because
		     * then it will run more slowly)
		     */

		    yy_next_state = yy_try_NUL_trans( yy_current_state );

		    yy_bp = yytext + YY_MORE_ADJ;

		    if ( yy_next_state )
			{
			/* consume the NUL */
			yy_cp = ++yy_c_buf_p;
			yy_current_state = yy_next_state;
			goto yy_match;
			}

		    else
			{
			goto yy_find_action;
			}
		    }

		else switch ( yy_get_next_buffer() )
		    {
		    case EOB_ACT_END_OF_FILE:
			{
			yy_did_buffer_switch_on_eof = 0;

			if ( yywrap() )
			    {
			    /* note: because we've taken care in
			     * yy_get_next_buffer() to have set up yytext,
			     * we can now set up yy_c_buf_p so that if some
			     * total hoser (like flex itself) wants
			     * to call the scanner after we return the
			     * YY_NULL, it'll still work - another YY_NULL
			     * will get returned.
			     */
			    yy_c_buf_p = yytext + YY_MORE_ADJ;

			    yy_act = YY_STATE_EOF((yy_start - 1) / 2);
			    goto do_action;
			    }

			else
			    {
			    if ( ! yy_did_buffer_switch_on_eof )
				YY_NEW_FILE;
			    }
			}
			break;

		    case EOB_ACT_CONTINUE_SCAN:
			yy_c_buf_p = yytext + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			yy_cp = yy_c_buf_p;
			yy_bp = yytext + YY_MORE_ADJ;
			goto yy_match;

		    case EOB_ACT_LAST_MATCH:
			yy_c_buf_p =
			    &yy_current_buffer->yy_ch_buf[yy_n_chars];

			yy_current_state = yy_get_previous_state();

			yy_cp = yy_c_buf_p;
			yy_bp = yytext + YY_MORE_ADJ;
			goto yy_find_action;
		    }
		break;
		}

	    default:
#ifdef FLEX_DEBUG
		printf( "action # %d\n", yy_act );
#endif
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	    }
	}
    }


/* yy_get_next_buffer - try to read in a new buffer
 *
 * synopsis
 *     int yy_get_next_buffer();
 *     
 * returns a code representing an action
 *     EOB_ACT_LAST_MATCH - 
 *     EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *     EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()

    {
    register YY_CHAR *dest = yy_current_buffer->yy_ch_buf;
    register YY_CHAR *source = yytext - 1; /* copy prev. char, too */
    register int number_to_move, i;
    int ret_val;

    if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
	YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

    /* try to read more data */

    /* first move last chars to start of buffer */
    number_to_move = yy_c_buf_p - yytext;

    for ( i = 0; i < number_to_move; ++i )
	*(dest++) = *(source++);

    if ( yy_current_buffer->yy_eof_status != EOF_NOT_SEEN )
	/* don't do the read, it's not guaranteed to return an EOF,
	 * just force an EOF
	 */
	yy_n_chars = 0;

    else
	{
	int num_to_read = yy_current_buffer->yy_buf_size - number_to_move - 1;

	if ( num_to_read > YY_READ_BUF_SIZE )
	    num_to_read = YY_READ_BUF_SIZE;

	else if ( num_to_read <= 0 )
	    YY_FATAL_ERROR( "fatal error - scanner input buffer overflow" );

	/* read in more data */
	YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
		  yy_n_chars, num_to_read );
	}

    if ( yy_n_chars == 0 )
	{
	if ( number_to_move - YY_MORE_ADJ == 1 )
	    {
	    ret_val = EOB_ACT_END_OF_FILE;
	    yy_current_buffer->yy_eof_status = EOF_DONE;
	    }

	else
	    {
	    ret_val = EOB_ACT_LAST_MATCH;
	    yy_current_buffer->yy_eof_status = EOF_PENDING;
	    }
	}

    else
	ret_val = EOB_ACT_CONTINUE_SCAN;

    yy_n_chars += number_to_move;
    yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
    yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

    /* yytext begins at the second character in yy_ch_buf; the first
     * character is the one which preceded it before reading in the latest
     * buffer; it needs to be kept around in case it's a newline, so
     * yy_get_previous_state() will have with '^' rules active
     */

    yytext = &yy_current_buffer->yy_ch_buf[1];

    return ( ret_val );
    }


/* yy_get_previous_state - get the state just before the EOB char was reached
 *
 * synopsis
 *     yy_state_type yy_get_previous_state();
 */

static yy_state_type yy_get_previous_state()

    {
    register yy_state_type yy_current_state;
    register YY_CHAR *yy_cp;

    yy_current_state = yy_start;
    yy_state_ptr = yy_state_buf;
    *yy_state_ptr++ = yy_current_state;

    for ( yy_cp = yytext + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
	{
	register YY_CHAR yy_c = (*yy_cp ? yy_ec[*yy_cp] : 1);
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
	    {
	    yy_current_state = yy_def[yy_current_state];
	    if ( yy_current_state >= 388 )
		yy_c = yy_meta[yy_c];
	    }
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	*yy_state_ptr++ = yy_current_state;
	}

    return ( yy_current_state );
    }


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *     next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( register yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
register yy_state_type yy_current_state;
#endif

    {
    register int yy_is_jam;

    register YY_CHAR yy_c = 1;
    while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
	{
	yy_current_state = yy_def[yy_current_state];
	if ( yy_current_state >= 388 )
	    yy_c = yy_meta[yy_c];
	}
    yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
    *yy_state_ptr++ = yy_current_state;
    yy_is_jam = (yy_current_state == 387);

    return ( yy_is_jam ? 0 : yy_current_state );
    }


#ifdef YY_USE_PROTOS
static void yyunput( YY_CHAR c, register YY_CHAR *yy_bp )
#else
static void yyunput( c, yy_bp )
YY_CHAR c;
register YY_CHAR *yy_bp;
#endif

    {
    register YY_CHAR *yy_cp = yy_c_buf_p;

    /* undo effects of setting up yytext */
    *yy_cp = yy_hold_char;

    if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
	{ /* need to shift things up to make room */
	register int number_to_move = yy_n_chars + 2; /* +2 for EOB chars */
	register YY_CHAR *dest =
	    &yy_current_buffer->yy_ch_buf[yy_current_buffer->yy_buf_size + 2];
	register YY_CHAR *source =
	    &yy_current_buffer->yy_ch_buf[number_to_move];

	while ( source > yy_current_buffer->yy_ch_buf )
	    *--dest = *--source;

	yy_cp += dest - source;
	yy_bp += dest - source;
	yy_n_chars = yy_current_buffer->yy_buf_size;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
	    YY_FATAL_ERROR( "flex scanner push-back overflow" );
	}

    if ( yy_cp > yy_bp && yy_cp[-1] == '\n' )
	yy_cp[-2] = '\n';

    *--yy_cp = c;

    /* note: the formal parameter *must* be called "yy_bp" for this
     *       macro to now work correctly
     */
    YY_DO_BEFORE_ACTION; /* set up yytext again */
    }


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif

    {
    int c;
    YY_CHAR *yy_cp = yy_c_buf_p;

    *yy_cp = yy_hold_char;

    if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
	{
	/* yy_c_buf_p now points to the character we want to return.
	 * If this occurs *before* the EOB characters, then it's a
	 * valid NUL; if not, then we've hit the end of the buffer.
	 */
	if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
	    /* this was really a NUL */
	    *yy_c_buf_p = '\0';

	else
	    { /* need more input */
	    yytext = yy_c_buf_p;
	    ++yy_c_buf_p;

	    switch ( yy_get_next_buffer() )
		{
		case EOB_ACT_END_OF_FILE:
		    {
		    if ( yywrap() )
			{
			yy_c_buf_p = yytext + YY_MORE_ADJ;
			return ( EOF );
			}

		    YY_NEW_FILE;

#ifdef __cplusplus
		    return ( yyinput() );
#else
		    return ( input() );
#endif
		    }
		    break;

		case EOB_ACT_CONTINUE_SCAN:
		    yy_c_buf_p = yytext + YY_MORE_ADJ;
		    break;

		case EOB_ACT_LAST_MATCH:
#ifdef __cplusplus
		    YY_FATAL_ERROR( "unexpected last match in yyinput()" );
#else
		    YY_FATAL_ERROR( "unexpected last match in input()" );
#endif
		}
	    }
	}

    c = *yy_c_buf_p;
    yy_hold_char = *++yy_c_buf_p;

    return ( c );
    }


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif

    {
    yy_init_buffer( yy_current_buffer, input_file );
    yy_load_buffer_state();
    }


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif

    {
    if ( yy_current_buffer == new_buffer )
	return;

    if ( yy_current_buffer )
	{
	/* flush out information for old buffer */
	*yy_c_buf_p = yy_hold_char;
	yy_current_buffer->yy_buf_pos = yy_c_buf_p;
	yy_current_buffer->yy_n_chars = yy_n_chars;
	}

    yy_current_buffer = new_buffer;
    yy_load_buffer_state();

    /* we don't actually know whether we did this switch during
     * EOF (yywrap()) processing, but the only time this flag
     * is looked at is after yywrap() is called, so it's safe
     * to go ahead and always set it.
     */
    yy_did_buffer_switch_on_eof = 1;
    }


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif

    {
    yy_n_chars = yy_current_buffer->yy_n_chars;
    yytext = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
    yyin = yy_current_buffer->yy_input_file;
    yy_hold_char = *yy_c_buf_p;
    }


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif

    {
    YY_BUFFER_STATE b;

    b = (YY_BUFFER_STATE) malloc( sizeof( struct yy_buffer_state ) );

    if ( ! b )
	YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

    b->yy_buf_size = size;

    /* yy_ch_buf has to be 2 characters longer than the size given because
     * we need to put in 2 end-of-buffer characters.
     */
    b->yy_ch_buf = (YY_CHAR *) malloc( (unsigned) (b->yy_buf_size + 2) );

    if ( ! b->yy_ch_buf )
	YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

    yy_init_buffer( b, file );

    return ( b );
    }


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif

    {
    if ( b == yy_current_buffer )
	yy_current_buffer = (YY_BUFFER_STATE) 0;

    free( (char *) b->yy_ch_buf );
    free( (char *) b );
    }


#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif

    {
    b->yy_input_file = file;

    /* we put in the '\n' and start reading from [1] so that an
     * initial match-at-newline will be true.
     */

    b->yy_ch_buf[0] = '\n';
    b->yy_n_chars = 1;

    /* we always need two end-of-buffer characters.  The first causes
     * a transition to the end-of-buffer state.  The second causes
     * a jam in that state.
     */
    b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;
    b->yy_ch_buf[2] = YY_END_OF_BUFFER_CHAR;

    b->yy_buf_pos = &b->yy_ch_buf[1];

    b->yy_eof_status = EOF_NOT_SEEN;
    }
# line 170 "lexer.l"


/************************************************************************
 * Function:	yyerror							*
 *									*
 * Description:	Writes a syntax error message reporting the unexpected	*
 *		token.							*
 ************************************************************************/

void yyerror (msg)
    char *msg;
{
    extern int yychar;


    if (yychar)
	error ("parse error before `%s'", yytext);
    else
	error ("parse error before end of input");
}


/************************************************************************
 * Function:	init_lexer						*
 *									*
 * Description:	Initializes the lexer for a new file.			*
 ************************************************************************/

void init_lexer (fp)
    FILE *fp;
{
    static int first_time = 1;


    if (first_time) {
	first_time = 0;
	yyin = fp;
    } else
	yyrestart (fp);

    filename = generator.filename;
}


/************************************************************************
 * Function:	update_line						*
 *									*
 * Description:	Updates the current line and file from a preprocessor	*
 *		directive.						*
 ************************************************************************/

static void update_line ( )
{
    char       *ptr1;
    char       *ptr2;
    int		line;
    static char include_filename [256];


    ptr2 = include_filename;
    line = strtol (yytext + 1, &ptr1, 10) - 1;

    if (ptr1) {
	generator.line = line;

	while (*ptr1 && *ptr1 ++ != '"');

	if (*ptr1)
	    generator.filename = filename;

	while (*ptr1 && *ptr1 != '"')
	    *ptr2 ++ = *ptr1 ++;

	*ptr2 = 0;
	if (ptr2 != include_filename)
	    generator.filename = include_filename;
    }
}

# undef yywrap
int yywrap ( ) {
    if (0) unput (0);
    return 1;
}
